<a href="https://colab.research.google.com/github/hritesh01/hritesh/blob/main/assignment1letsupgrade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
x=np.where(arr==7)


In [8]:
print(x)

(array([1]), array([0]), array([0]))


In [9]:
x=np.where(arr % 2==0)

In [10]:
print(x)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 1, 0, 1, 1]), array([1, 0, 2, 1, 0, 2]))


In [11]:
for i in np.nditer(arr):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [12]:
x=np.where(arr % 2 == 1)
print(x)

(array([0, 0, 0, 1, 1, 1]), array([0, 0, 1, 0, 0, 1]), array([0, 2, 1, 0, 2, 1]))


In [13]:
print (np.sort(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
